### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/WhereYouGo#106]
As discussed in some PR we could do a new release based on the current status of the master branch.

Question:
- Shall we merge master to release right now or is any important change still in progress?

**Comment by bekuno** [comment]
We can now start with a beta release to check if the changes for Android 8 and the landscape method are fine.

**Comment by Lineflyer** [comment]
I doubt that beta versions make any sense given that we only have around 200 beta subscribers (last time I looked it up). We can IMHO smoke test and directly release.

**Comment by bekuno** [comment]
My idea was to publish a beta release now, update the strings in the meantime by crowdin and publish the final release afterwards.
It seemed to me that through the last beta release a number of users had signed up for the beta program.

**Comment by Lineflyer** [comment]
Fine for me.
So, shall I merge `master` to `release` to build a beta release or is there anything we need to complete upfront?

**Comment by bekuno** [comment]
I am not aware of any open points to solve first.
So please start the merge.

**Comment by Lineflyer** [comment]
`release` has been fast forwarded to the head of `master`. So the branches are now even.
However I forgot to check/update release notes. Will do this asap.

**Comment by Lineflyer** [comment]
Version 2020.04.07 is out for beta testing. Current registered testers: 1200.

**Comment by bekuno** [comment]
We should add "Allow the app to run in landscape mode" to the release notes.

**Comment by Lineflyer** [comment]
Feel free to add it (on release branch).
We can think about rebuilding it to have it included when going from beta to production.

BTW: The beta is still not online yet, seems Google now really takes longer to process the publish.

**Comment by Lineflyer** [comment]
Beta version still not online. Google taking time to review. :(

**Comment by Lineflyer** [comment]
Beta version is still not online. I wonder If I should directly promote it to a full version, otherwise we might need 2x up to 7 working days + beta time to get anything out on the market in the current situation.

**Comment by Lineflyer** [comment]
Beta version is online since yesterday.
Up to now no crash reports on Google Play. Will contact a user with Android 8 problem, whether it is solved for him.

**Comment by Lineflyer** [comment]
Still no crash reports from Google Play (which could also mean, that our beta user base is to small) but one user confirmed its working for him on Android 8.
To get more feedback I will promote version 2020.04.07 to a live version now. Release is done.
