### ISSUE TITLE
Connection error if no username/password configured

### ISSUE THREAD

**Issue by bekuno** [cgeo/WhereYouGo#11]
When trying to download a cartridge (e.g. initiated by c:geo) then there is no check if username/password configured. If nothing configured then the app gives an I/O error:
![20200113_231845](https://user-images.githubusercontent.com/32555742/72296998-3a85ea00-365b-11ea-9f05-8444da8e4cac.png)

(see DownloadCartridgeActivity DownloadTask(DownloadCartridgeActivity.this, username, password); )

**Comment by SchoolGuy** [comment]
Please assign me to this one. I will sit down at the weekend and improve this (if you are not already on it).

**Comment by bekuno** [comment]
@SchoolGuy Ok, have fun :-)
At least two points to solve
- no useable credentials (no username and/or no password)
- false credentials (user name false (does no more exist) or password wrong)

**Comment by SchoolGuy** [comment]
Okay we have various choices how I can solve this:

* Display a long toast that no credentials are configured when clicking the Download Button and then doing nothing.
* Disabling the download button when no credentials are configured and displaying above mentioned toast at the same time.
* When clicking the download button with no credentials then just redirect to the settings activity where they are configured

If the Username and Password is wrong we also have multiple options but I would go for a human readable error message in above screenshoted window.

@bekuno Any wishes or suggestions?

**Comment by SchoolGuy** [comment]
@Lineflyer Maybe you also got an opinion on this one.

**Comment by bekuno** [comment]
We should do it as easy as possible for the user.
If no credentials are configured then my favorite is to disable the download button and present a window with an information text and a button to redirect to the credentials activity.

**Comment by SammysHP** [comment]
Toasts are deprecated. Can't we just show a warning next to the button or somewhere else on the screen? Maybe red with a waning icon and a link to the settings.

**Comment by SchoolGuy** [comment]
@SammysHP I looked for half an hour why and at what point Toasts got deprecated. I did not find a confirmation on that. The official Android Docs are also not stating a deprecation warning on API Level 29: https://developer.android.com/reference/android/widget/Toast

**Comment by SammysHP** [comment]
You might be right. I can't find any explicit statement as well. But I think I've read it a few years ago somewhere with something about that they are so short-lived and easy to miss by the user.

**Comment by SchoolGuy** [comment]
@SammysHP Well you are probably right about this one. I will think of something which is more explicit.

**Comment by Lineflyer** [comment]
I just accidentally checked this behaviour after having installed WhereYouGo and triggering a download from c:geo. 
I do not see such kind of erroe butbthe app directly brought me to the credential configuration screen after logging in failed.

**Comment by bekuno** [comment]
@SchoolGuy 
As written in comment https://github.com/cgeo/WhereYouGo/issues/11#issuecomment-593997498
and also confirmed in my tests the error was gone.
Maybe there is an other probem with the communication and an uncaught error.

**Comment by Lineflyer** [comment]
@SchoolGuy Still on it?

**Comment by SchoolGuy** [comment]
@Lineflyer Every time I don't have a WIP PR I forget to work on it. I am open Android Studio now and I expect to have something ready to be reviewed by Sunday.

**Comment by bekuno** [comment]
Today I had time to test the PR #172.

> At least two points to solve
> 
>     * no useable credentials (no username and/or no password)
>     * false credentials (user name false (does no more exist) or password wrong)

The first point will solved by #172.
For the second I created issue #182.

The initial screenshot is related to `DownloadCartridgeTask.init()`
Maybe the message could be optimized, but the is at low prio.
