### ISSUE TITLE
define in app used translations

### ISSUE THREAD

**Issue by bekuno** [cgeo/WhereYouGo#126]
Our inofficial rule in c:geo is to only add new languages if they have ~50% or more translated. (see https://github.com/cgeo/cgeo/pull/8023). This seems a idea to not too much mix few native translations with mostly English.
But with the crowdin integration currently all defined languages are transferred, also the new languages with 0% approved: Slovenian, Svedish, Turkish  
Can we limit the exchange from/to crowdin in the yaml file?
Or is the definition as in c:geo within main/build.gradle:
~~~
android {
    defaultConfig {
        // include only those language resources from libraries which we actively maintain ourself in the translation project
        resConfigs "en","ca","ceb","cs","da","de","el","es","fi","fr","hu","it","ja","ko","lt",...
~~~
a usefull solution?

edit:
for the second solution see https://developer.android.com/studio/build/shrink-code#unused-alt-resources

**Comment by bekuno** [comment]
We should define resConfig independent from the problem of the cromwdin problem to remove also unsupported languages which are imported from included ressources, see https://blog.egorand.me/a-curious-case-of-multiple-locales/ (not using "auto", which is now deprecated)

**Comment by Lineflyer** [comment]
The only thing I can do on Crowdin is to switch off filling untranslated strings with source (english) strings. But we explicitly enabled this years ago in c:geo in order to have the same file content in all languages.

I am asking myself, who enabled those new languages? I did not and I already removed quite some of them (like Georgian, Serbian, etc.)

**Comment by bekuno** [comment]
> I am asking myself, who enabled those new languages? I did not and I already removed quite some of them (like Georgian, Serbian, etc.)

I did.
I took a look at the current used languages of cgeo and adopted these.

**Comment by bekuno** [comment]
Lets use the second variant.
So we need no extra thinks for crowdin to c:geo.
