### ISSUE TITLE
Check supported API versions

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/WhereYouGo#13]
Now that we have access to the Play console I have seen, that currently different APK packages are published covering a variety of different API levels.

This does IMHO not look so meaningful and needs to be flattened:

![2020-01-14 22_39_21-App-Releases - WhereYouGo - Google Play Console](https://user-images.githubusercontent.com/949669/72385056-fb20d180-371e-11ea-9faf-a2260b84c511.png)

**Comment by Lineflyer** [comment]
Does anyone have an idea about this release setup?

The clear part for me is, that the app versions for lower API levels as currently supported (below 15) have been kept, which is perfectly fine as they will work on those devices as a legacy version.
What I do not understand is, that version codes 43 and 45 both use same minSDK and targetSDK but both APK are shown as active...

**Comment by hakuchi** [comment]
Can this are the beta and non beta versions?

**Comment by Lineflyer** [comment]
No, at least it all listed in production rather than beta. It might however be, that former betas have been taken to production which makes no sense, as Google will only provide the highest version code with matching API range to users.

**Comment by Lineflyer** [comment]
No need to futher check it:
I had to disable all those old versions while publishing our initial version 2020.03.08.

Our minSDK is now 15., targetSDK 28.
