### ISSUE TITLE
App stürzt immer wieder ab 

### ISSUE THREAD

**Issue by TomFlecke** [cgeo/WhereYouGo#147]
Laden der Cartridge und finden des Startpunktes funktionieren einwandfrei. Aber leider stürzt die aktuelle Version beim Erreichen des ersten Wegpunktes ab. Gerät ist ein S7Edge mit Android 8.0.0

**Comment by Lineflyer** [comment]
Dieser Fehler sollte mit der aktuellen Beta-Version bereits behoben sein.

Aktiviere gerne die Teilnahme am Beta-Programm hier:
https://play.google.com/apps/testing/menion.android.whereyougo

Eine Rückmeldung, ob es funktioniert, wäre prima.
