### ISSUE TITLE
Provide possibility to verify login data in settings

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/WhereYouGo#188]
From the different support mail I do see one clear pattern:

Some users seem to be confused, that after entering their username and password they do not see any login/done button. 
Although this is technically not needed it would IMHO be wise to have at least a "save" button or (better) a real possibility to verify the login data towards the wherigo.com server.

**Comment by SchoolGuy** [comment]
Assign me to this. After my PR is merged, I will do a new one for this.

**Comment by bekuno** [comment]
@SchoolGuy Are you able to work on this PR?

**Comment by SchoolGuy** [comment]
@bekuno Damn I totally forgot about this one. I will start tomorrow when I am home again.
