### ISSUE TITLE
Meet Google Play's target API level requirement

### ISSUE THREAD

**Issue by bekuno** [cgeo/WhereYouGo#2]
Since 1. November 2019 it is necessary to define targetSdkVersion to 28 (Android 9).
See
https://developer.android.com/distribute/best-practices/develop/target-sdk
https://support.google.com/googleplay/android-developer/answer/113469#targetsdk

**Comment by Lineflyer** [comment]
@bekuno Are you planning to resubmit the PR you prepared in the old repo?
