### ISSUE TITLE
target Android 10 (API level 29)

### ISSUE THREAD

**Issue by bekuno** [cgeo/WhereYouGo#209]
From 2 November 2020, app updates must target Android 10 (API level 29) or higher.

see https://developer.android.com/distribute/best-practices/develop/target-sdk

Beside setting `targetSdkVersion` and `compileSdkVersion` for the master and legacy branch we have to check if some further code changes are needed.

@moving-bits Do you noted special points from c:geo switch to api29?

**Comment by moving-bits** [comment]
IMHO the most important part is the necessary rework of file access, as Android switches to Storage Framework starting with API 29, see https://github.com/cgeo/cgeo/issues/8457.

There is a workaround for using Android 10 (see https://github.com/cgeo/cgeo/pull/8473), but starting with Android 11 the new Storage Framework gets enforced for all apps targeting API level 29 or higher, which would effectively mean that WhereYouGo wouldn't be able to access its local files stored in user-reachable directories any longer.

IMHO we have two choices:
- Stay with targetDSK < 29 for now and as long as we dont _have_ to update. => This would keep WhereYouGo working an Android 11 as well (AFAIK).
- Switch to targetSDK29 and immediately start working on implementing the new Storage Framework. WhereYouGo may be easier to switch than c:geo as it is smaller, so it could be sort of a training case.

**Comment by Lineflyer** [comment]
mmh..coming back to this issue:
According to the latest results in c:geo development we should taken action for WhereYouGo at least to keep compatability to Android 11:
- I assume we do not use "requestLegacyExternalStorage" with WhereYouGo yet
- We can no longer easily push an update starting in a few days (November 1st, 2020) due to the targetSDK still being 28 by now

Shouldn't we at least push a quick one just adding the "requestLegacyExternalStorage" before end of this week?

@bekuno

**Comment by moving-bits** [comment]
> Shouldn't we at least push a quick one just adding the "requestLegacyExternalStorage" before end of this week?

We do not necessarily have to publish it already, as the current version will continue to work for now.

To be prepared if we need some urgent update, we should provide a PR with targetSDK 29 and the `requestLegacyExternalStorage` flag set to true, and give it some testing for possible side effects.

**Comment by Lineflyer** [comment]
So you mean it will work on Android 11 without "requestLegacyExternalStorage"  as long as we target SDK28?

**Comment by moving-bits** [comment]
> So you mean it will work on Android 11 without "requestLegacyExternalStorage" as long as we target SDK28?

No, not on Android 11 devices (at least not without the flag), AFAIK.

I was along the line of Play Store enforcing their updated targetSDK rules: Not complying to new targetSDK rule only prevents us from pushing an update, but does not break the existing installations.

So we still need to update to targetSDK 29 - at some point in time, but not necessarily before the changed policy in Play Store gets set active.

**Comment by Lineflyer** [comment]
I have to admit, that I lost the line:
Will the current release version (target 28, without legacy storage) work on Android 11? 
If no: If we want to quickly gain compatability we need to push an update (target 28, with legacy storage) before end of October, or am I missing something?

**Comment by moving-bits** [comment]
Ah, you're right - I've been confused (or mixed up two things). If I'm not mistaken (but it's been a long day today...):
- apps targeting SDK 28 or lower should continue to work under Android 11 in their usual way, but will not be able to be updated starting beginning of November, as Play Store raises their min targetSDK requirement
- apps targeting SDK 29 can use the flag `requestLegacyExternalStorage`
- apps targeting SDK 30 or higher cannot use that flag any longer (resp. it will be ignored, even if set)

So WIG should continue to work with SDK 28 even on Android 11.

But to be sure maybe someone can fire up an Android 11 device or emulator with current WIG on it and test this.

**Comment by Lineflyer** [comment]
> But to be sure maybe someone can fire up an Android 11 device or emulator with current WIG on it and test this.

Will do!

**Comment by Lineflyer** [comment]
> apps targeting SDK 28 or lower should continue to work under Android 11 in their usual way,

Tested on the Pixel 3 running Android 11 with WhereYouGo 2020.08.21 (latest PlayStore):
- The default folder for cartridge download is still acceesible
- Can download and run cartridges with that
- Selecting a random cartridge folder works (e.g. selecting /cgeo/gpx)
- Could not test offline map files (as I do not have any V3 on this device) but the dir chooser works and show all files

Seems 2020.08.21 is "fit" for Android 11.

So the only relevant point in this issues context is, that we should apply "requestLegacyExternalStorage" once we target SDK29.
