### ISSUE TITLE
Support crowdin translation for WhereYouGo

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/WhereYouGo#23]
Same as for c:geo also WhereYouGo could take advantage of crowd based translation contribution using crowdin.org

**Comment by bekuno** [comment]
The user "cgeo" should create the project because the owenership is not changeable.
@Lineflyer You task?

**Comment by rsudev** [comment]
Currently I am in charge of this crowdin account. Will create the project ASAP.

**Comment by rsudev** [comment]
Open-Source project request submitted (as open source project you can apply to a free tier of their offering)

**Comment by Lineflyer** [comment]
According to mail from @rsudev this is done. @rsudev How to access it?
Shall we also try the new enterprise workflow?

**Comment by bekuno** [comment]
@rsudev 
What is the state?

**Comment by rsudev** [comment]
@bekuno Thanks for pinging me. I was a bit puzzled as to what the next steps would be (as I was not the original creator of the cgeo project on crowdin), but now I actually created the project, so strings can be uploaded, translations started...
I started with selecting German and French as target languages, others can be added at any time.
All managers for cgeo on crowdin are also invited as managers for WhereYouGo.

**Comment by rsudev** [comment]
> According to mail from @rsudev this is done. @rsudev How to access it?
> Shall we also try the new enterprise workflow?

I think we can give it a spin. Shall I start by creating an enterprise space for c:geo?

**Comment by moving-bits** [comment]
@rsudev  Thanks for setting that up.

@rsudev / @Lineflyer  What can the enterprise workflow be used for?

**Comment by Lineflyer** [comment]
Not sure about the enterprise workflow...need to read through it as time permits.

The workspace for WhereYouGo on Crowdin is prepared but as of now no source strings have been uploaded.
Can someone with knowledge upload the source strings and (ideally) also the already translated strings to have a base for involving the crowd?

**Comment by bekuno** [comment]
> Can someone with knowledge upload the source strings and (ideally) also the already translated strings to have a base for involving the crowd?

I would try to realize it if no one with deeper knowledge and spare time wants to do so. 
But I have to learn the deeper details for Crowdin and find a good mapping from the code to a crowdin structure.
And second, we need an import/export function, either as realized in c:geo or with a crowdin/github API.

**Comment by Lineflyer** [comment]
> I would try to realize it if no one with deeper knowledge and spare time wants to do so.
But I have to learn the deeper details for Crowdin and find a good mapping from the code to a crowdin structure.
And second, we need an import/export function, either as realized in c:geo or with a crowdin/github API.

That would be highly appreciated.
I just gave it a manual try. Not too complicated IMHO.
I managed to upload source strings and existing translations (quite comfortable via zipped xml files) of the release branch to the project on Crowdin. 

So for now translation is somehow enabled as interim solution.

**Comment by Lineflyer** [comment]
@bekuno 

I have seen you started something with regard to crowdin integration towards Github. Did you make any progress with that or have time to continue looking into it?
Otherwise you could drop the current state, so I could take a look. Currently I cannot access this part of Github settings as it states that you are in progress of configuring it.

**Comment by bekuno** [comment]
@Lineflyer I stopped my attempt to configure the GitHub integration because I was only allowed to connect crowdin to my private repositories. Now this attempt is deleted.

**Comment by Lineflyer** [comment]
I tried to set it up now, which was OK in principle but the result is not OK.

The working mode of the Crowdin integration is, that it reads files to be translated from the repo (using a user defined pattern) and pushes all translations to the branches `l10n_master` or `l10n_release` matching to the individual base branches using a pattern constructor for directory and file name of the translated files. This configuration is stored in a YML file in the root of each branch.

As you may see it works so far, that branches have been created and populated with resulting commits. However AFAICS right now all incoming translations are basically a complete reset to the English source. No idea, why that happens.

Will try to investigate tonight.

If the basic functions work, I will look deeper into detailed things like:
- [ ] A commit is done for each file in each language. I wonder if this can be done in another way to minimize the clutter and maximize the overview
- [ ] It seems the dialects of Portuguese (Brazilian and Portuguese) are lost in this construction. I can define the android language code being used for directory names (e.g. pt-rBR) but then it is used for all languages. Need to look up if it can be defined as exception.
- [ ] Fine tune sync intervals. AFAICS it is set up to pull and push every 10 minutes. It should be possible to setup a hook for pulling and pushing can be reduced to e.g. 24 hours.

**Comment by Lineflyer** [comment]
Quick edit and reminder to myself:
The reason for untranslated strings coming in seem to be, that the automated source file fething from our repo includes the respecive directory structure whereas the first manual approach did not.
Thus Crowdin recognizes these files as different files with same name and considers them untranslated.
Now the challenge is to work with the new files without loosing the work on the old files.

**Comment by Lineflyer** [comment]
Question to the developers:
Is it possible that we generally use the android languages codes instead of the two letter codes?

Example German localization:
Current two letter code `/values-de/`
Android code: `/values-de-rDE/`

It seems there is no way to define an exception for some languages only on Crowdin or - to be precise - it seems you can configure it but it has no effect.

**Comment by Lineflyer** [comment]
Regarding those dialects I found the solution in some internet thread. Actually the exceptions have to be defined before the integration is set up. I retried from scratch and now it works.
Sorry for the many commits and deletions and the associated mails.

Regarding the ToDo items above:
-Commits: It is possible to modify the commit message itself but not the seperation into each file. It should however be not a problem once the first large PR has been merged as it is then expected only to see proofread changes every 24 hours as a commit.

- Sync frequency: Can be set to 24 hours once the inital merge has been done (see above)

- Use other user than myself: The integration can be set up using another users access token. Will try with the cgeo-ci-bot (who is defined as outside collaborator). This sadly also means I need to redo everything one more time....but not a big deal, only many commit messages.

**Comment by Lineflyer** [comment]
Update:
I used the user "cgeo-ci-bot" to setup the integration from Crowdin once again (by generating an access token from that user) using the same working configuration I figured out yesterday. It works as expected so far and I merged incoming strings already.

However there is one thing, which needs investigation:
After merging the proposed translations from Crowdin (i.e. merging `l10n_release` into `release` and additionally merging `release` into `master` to stay in sync), the branch `l10n_release` still remains and further changes coming in from Crowdin are added as commits on top of these branches. 

I am not sure why this happens. 
I assume we either need to do a clean merge commit (I squashed the commits while merging) to allow Crowdin to track, what has been merged. This however would result in tons of seperate file commits in our version history, which is not desirable at all. 
The other option would be to delete the `l10n_*` branches when merging, so Crowdin will recreate them based on the current state of the head branch. Thats hopefully the desired working mode.

Strange enough the manual on the Crowdin help center, does say **NOTHING** about how to merge the branches into our repo.

**Comment by Lineflyer** [comment]
And another update:
From reading the web I learned, that indeed the desired workflow is to delete the `l10n_*` branch after merging and let Crowdin recreate it on the next push event which will then automatically base it on the current state of the base branch.

Thats perfectly fine, as it can be done with one click after merging the PR.
But due to this merging and branching workflow I decided to skip the handling of both branches (release and master) and base the Crowdin integration on `master` only.
IMHO this has no disadvantages:
- Most of the time new strings are caused by new feature and should thus be on `master` first anyway.
- It allows more time for contributors to provide translations as new strings will only be present on `release` immediately before releasing a beta/production version
- No further need to merge translation between `release` and `master` to make commits consistent and make Crowdin (and us) happy.

I will finalize the integration accordingly and then do some final tasks:
- [ ] Reduce push period to 24 hours (new translation auto-pushed once per day)
- [ ] Write Wiki article about how to set up and how to use the Crowdin integration
- [ ] Crosscheck security settings and permissions for "cgeo-ci-bot" on Crowdin and Github

**Comment by bekuno** [comment]
@Lineflyer Many thanks for the huge work, diving in the crowdin details and also documenting all together.

**Comment by Lineflyer** [comment]
> @Lineflyer Many thanks for the huge work, diving in the crowdin details and also documenting all together.

Youre welcome.
At the end it was a nice possibility to do something else than homeoffice work and watching TV ;)

**Comment by moving-bits** [comment]
> @Lineflyer Many thanks for the huge work, diving in the crowdin details and also documenting all together.

I second this, thanks @Lineflyer for putting this together!

**Comment by Lineflyer** [comment]
> @Lineflyer Many thanks for the huge work, diving in the crowdin details and also documenting all together.
> 
> 
> I second this, thanks @Lineflyer for putting this together!

Thanks! :) What about doing the same for c:geo (see my comment in some issue over there)?

**Comment by moving-bits** [comment]
Sounds pretty useful to me.
