### ISSUE TITLE
Light theme text problem in cache details

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/WhereYouGo#235]
Reported via support mail:

**Detailed steps causing the problem:**
- use c:geo light theme
- Open cache details of a cache having a colored text (reported example: GC8ZV6F)
- Scroll in the listing to „Von der 1.Bonusinfo peilt ihr die Hälfte der 2.Bonusinfo Meter in 3. Bonusinfo Grad“

**Actual behavior after performing these steps:**

Some words have a black background and are not readable.

**Expected behavior after performing these steps:**

Text is always readable independently from color.

**Version of c:geo used:**

2020.11.03

**System information:**

Huawei p smart

**Comment by bekuno** [comment]
Recreated as c:geo issue.

**Comment by Lineflyer** [comment]
ups....Thanks!
