### ISSUE TITLE
switch to minSdk 21

### ISSUE THREAD

**Issue by bekuno** [cgeo/WhereYouGo#266]
For the update of the locus integration we have to switch to minSdk 21.
This is already the prerequsites in c:geo.
I think we can configure the current release as a legacy version as we have done in c:geo.

What do you think?

**Comment by Lineflyer** [comment]
> I think we can configure the current release as a legacy version

This is about a dependency, isnt it?
So whatever is currently configured on our legacy branch will stay as it is. Or do we need to take any action?

**Comment by Lineflyer** [comment]
ah...wrong repo. This is Whereyougo. 

We could define a legacy version, but we need to look at branches and CI to prepare a legacy build environment.

**Comment by bekuno** [comment]
@Lineflyer 
My idea: Before pushing master to release
 - renaming branch `legacy` to `legacy_api15`
 - set `         maxSdkVersion 20` for branch `release`
 - create a version for the Play Store
 - copy branch  `release` to `legacy_api16-20`

If the user of WhereYouGo have similar Android version as the c:geo user than there are only few user at the old release. So the legacy version must not be in maintenance, but installable.

**Comment by Lineflyer** [comment]
We have to consider:
- We need a proper CI build environment for a legacy build
- Whatever shall be published via Google Play needs to meet target SDK=29. That is to be used independent of minSDK / maxSDK AFAIK. Do we meet this requirement for the planned branches/releases?

**Comment by bekuno** [comment]
>     * Do we meet this requirement for the planned branches/releases?

The release has `targetSdkVersion 28`, master has `29`.
I will check if we need aditional changes for release.
If we can not change the targetSdk for release then I suggest to not create a legacy release on the Play Store.

**Comment by Lineflyer** [comment]
A short update on this one. It could still be possible to provide a legacy build:
- Currently ´master` is on targetsdk=30 to meet Google requirements (also a potential legacy build needs to fulfill that)
- Before changing to minSDK=21 we should update `legacy` to the status of `master` 
- Then we can change the minSDK to 21 on `master`.

If I did not forget something, this should bring us to a state to push a final working `legacy` to the old APIs.
CI build for the legacy release should have been properly configured meanwhile.
