### ISSUE TITLE
WhereYouGo - Call for developers 

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/WhereYouGo#283]
As discussed in the last c:geo dev meeting I will issue a Call for Developers once again over the WhereYouGo Facebook page -> Crosspost to c:geo Facebook page

There is already a call for developers within the app and on the landing page https://www.whereyougo.org

**Comment by Lineflyer** [comment]
- Posted on the WhereYouGo facebook page
- Crossposted to c:geo
- Shared to some german facebook geocaching groups (incl. c:geo Fangruppe)
- Put warning on c:geo homepage targeting the WhereYouGo landing page
- Highlight "Call for developers" on WhereYouGo landing page

**Comment by SchoolGuy** [comment]
@Lineflyer I think also important is the fact that more people should be able to merge and review PRs. We have seven open PRs and I see no progress in any of them. I would have been able to start on the Mapsforge Support or even more redesigns if my previous work would have been accepted. I know that we are running on a volunteer basis but that doesn't change the fact that for example we have no explanation of the current PR workflow or what standards we use in regard of coding. Just my two cents about this. :)

**Comment by bekuno** [comment]
@SchoolGuy At first I will you say many thanks for your work. 
Currently we try to adapt the workflows/standards from c:geo. 
We hope to find more people than you who wants to develop on WhereYouGo. 
Maybe a deeper integration in c:geo or other synergies beetween both apps will move forward WhereYouGo.
See also the discussion in https://github.com/cgeo/cgeo/issues/10087 .

**Comment by SchoolGuy** [comment]
Okay. I will learn for my final papers in may and have a deeper look in the evening. Maybe I can find some other cachers who are programmers to contribute here. I know quite a few but never have worked with one of them.

**Comment by thejensi1** [comment]
Hi, I heard your call for developers and hopefully I can contribute :) But first some facts about myself: 
I'm originated in Germany, am a software engineer for several years (mostly Java & C#) and (of course) a geocacher.
I would like to take part in developing/enhancing the WhereYouGo app as I used it several times already and would love to see it getting more enhanced :)
I would like to start getting myself a bit familiar with the code and see if I can get it compiled and running - so fingers crossed.

**Comment by SchoolGuy** [comment]
@thejensi1 The standard in Android is AndroidStudio. For me it was just a git clone and open in AndroidStudio, everything worked then out of the box!

**Comment by bekuno** [comment]
> 
> 
> Okay. I will learn for my final papers in may and have a deeper look in the evening. Maybe I can find some other cachers who are programmers to contribute here. I know quite a few but never have worked with one of them.

At the first place is your best graduation.
The hobby project has to wait.
I wish you great success.

**Comment by Lineflyer** [comment]
> I would like to start getting myself a bit familiar with the code and see if I can get it compiled and running - so fingers crossed.

Great to hear. Feel free to report back here in case you have any questions.

**Comment by GJMMelb** [comment]
Hi, I also heard your call for developers and am happy to contribute if I can. I am not a developer but I do program in Java. I am a geocacher in Australia and I am familiar with whereyougo.

**Comment by bekuno** [comment]
> 
> 
> Hi, I also heard your call for developers and am happy to contribute if I can. I am not a developer but I do program in Java. I am a geocacher in Australia and I am familiar with whereyougo.

Every contribution is fine. Not only code development, also e.g. deep tests or design.
Feel free to report back here in case you have any idea or questions.

**Comment by Lineflyer** [comment]
Closing this action for now...
I will keep posting on the social channels from time to time anyway.
