### ISSUE TITLE
No GPS on Android 12

### ISSUE THREAD

**Issue by joemadder** [cgeo/WhereYouGo#306]
It is not possible to activate the GPS on a Pixel 6 Pro with Android 12.
If you try to switch it on, you are offered to go to the system settings and switch on the location release, which is already permanently released.
According to a forum post, the problem also exists on a Pixel 5 with Android 12 and looks like a general Android 12 problem.

**Comment by Lineflyer** [comment]
Will take a look into this problem via emulator or my Android 12 device as time permits.
I fear, that the legacy permission system might run into problems as WhereYouGo is way behind and (at this moment) not well maintained due to lack of ressources.

**Comment by lukasMK89** [comment]
Unfortunately, this bug is caused by really new security in the Android 12 GPS API.
The same problem is currently being reported on Samsung S21 owners after the update on Android 12...

**Comment by Lineflyer** [comment]
Confirmed.
`master` is running normal on Android11, on Android 12 however the app claims, that location service is not enabled on the device although it is active and permission has been granted upon install.

![image](https://user-images.githubusercontent.com/949669/144900842-63189287-ffaa-4918-86fe-41ec371297b8.png)

This means we should either fix it and thus also potentially need to do more changes to bring WhereYouGo on targetSDK>=30 (see #274)
Or discuss again about a possible integration into c:geo.
