### ISSUE TITLE
Looks like I don't have permission to grant testing for WhereYouGo

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/WhereYouGo#323]
Looks like I don't have permission to grant testing for WhereYouGo

_Originally posted by @eddiemuc in https://github.com/cgeo/WhereYouGo/issues/322#issuecomment-991763513_

Need to check whitelisting on CI to refer to matching org access level for WhereYouGo

**Comment by bekuno** [comment]
I added @eddiemuc and @fm-sys to the CI Build GitHub Pull Request Builder admin list.
