### ISSUE TITLE
WhereYouGo not using correct default language

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/WhereYouGo#329]
## Bug description

My device is setup to use German language.
When starting WhereYouGo it behaves kind of strange:
- In the beginning the main menu was shown in German and also all strings also in German except that all strings in "Settings" are english.
- When using Settings - Localization - Language and setting it to "German" the whole app uses German strings
- When using Settings - Localization - Language and setting it to "System Default" the whole app is in English from then on

## WhereYouGo version

2021.12.25-NB

## Reproducible

Kind of...at least something is fishy here

## System information
Android 11, Samsung S20

**Comment by Lineflyer** [comment]
@SchoolGuy @moving-bits 
Do you happen to find time to look into the default language detection here?
It seems when I set WhereYouGo to "System default" it keeps using english despite my device is set to german.

That would be a regression in a possible new version.

**Comment by sk-juroot** [comment]
I have tried my best to get this on time, since I have limited access to my dev rig on these days.
Hotfix details can be found in PR #332

**Comment by Lineflyer** [comment]
Solved with b66c895. Thanks @sk-juroot
