### ISSUE TITLE
No icon for the app indicator

### ISSUE THREAD

**Issue by bekuno** [cgeo/WhereYouGo#345]
### Describe your problem!

When WhereYouGo is active a app indicator is shown.
Now it is only a gray circle.
It should be the WYG icon.

### How to reproduce?

- Start WYG
- look at the system app indicators

 

### Actual result after these steps?

- on my device:  (status line, near the clock)
![Screenshot_20220104-114525_WhereYouGo](https://user-images.githubusercontent.com/32555742/148058268-1617b00f-b509-4bec-92cb-a6dbbd38d43b.jpg)
- app info:
![Screenshot_20220104-114500_WhereYouGo](https://user-images.githubusercontent.com/32555742/148058275-605822fb-4c84-4f42-826a-717de3503c75.jpg)

### Expected result after these steps?

This should show the (new) WYG icon

### Reproducible

Yes

### WhereYouGo Version

2022.01.02

### System information

```text
Samsung Note 8, Android 9
```

**Comment by sk-juroot** [comment]
Can't even remember the times when WYG has correct icon in status bar 😅 Tought that current circle is intentional.

**Comment by bekuno** [comment]
There are many improvements possible. 
With the new icon set it should be easier to configure this icon. 
I dont know if it had another icon before.
