### ISSUE TITLE
Dependency to external mapsforge implementation?

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/WhereYouGo#347]
Just found this in build.gradle:
https://github.com/cgeo/WhereYouGo/blob/35b4fe547a464d42a095f9fcb8abbd19fadc7792/build.gradle#L115

Does it mean we are using some others repo mapsforge implementation in WhereYouGo?

**Comment by sk-juroot** [comment]
According to https://github.com/jspricke/mapsforge-map-whereyougo readme, the only difference from the original Mapsforge 0.3.1 library should be the `onTap()` method on Overlay. Just from the quick peak trough WYG code, it may not be necessary to implement this kind of custom event with upgraded Mapsforge to latest version.

**Comment by bekuno** [comment]
Correct. From history https://github.com/jspricke/mapsforge-map-whereyougo/commits/master - the commit on Jan 16, 2013 is https://github.com/mapsforge/mapsforge/commits/0.3.1 , all later commits looks related to onTap.

**Comment by SchoolGuy** [comment]
So the goal to close this issue is, to upgrade the Mapsforge code? Because if this is the goal then I believe this is a duplicate.

**Comment by Lineflyer** [comment]
The dependency will be no longer needed once we use a newer mapsforge version.
It will be  implicitly fixed by using the newer mapsforge version.
