### ISSUE TITLE
Setup repo dedicated teams for access right levels to the repo

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/WhereYouGo#356]
At this moment the WhereYouGo repo access rights are coupled to the cgeo organization teams.

A dedicated team structure (e.g. team + core as in c:geo) should be setup to allow adding contributors to these teams providing more access rights (i.e. team= all permission except pushing and admin / core = all permissions except admin).

**Comment by Lineflyer** [comment]
Work in progress:
- [x] Created new teams @cgeo/whereyougo-core  and @cgeo/whereyougo-team 
- [x] Assigned all members of @cgeo/core which have in the past contributed to WhereYouGo repo into @cgeo/whereyougo-core 
- [x] Setup repo access and push limitation to the newly created teams
- [x] Remove cgeo teams from the repo access afterwards
- [ ] Test access rights  --> @eddiemuc  I did not add you yet to any of the whereyougo teams, so you should e.g. not be able to close or set new labels to a random issue and not be able to push to WhereYouGo. Could you test that?
- [ ] Add remaining members of @cgeo/team to @cgeo/whereyougo-team 
- [ ] Need to send invitation to recent contributors e.g. @SchoolGuy @sk-juroot to join @cgeo/whereyougo-team

**Comment by eddiemuc** [comment]
> * Test access rights  --> @eddiemuc  I did not add you yet to any of the whereyougo teams, so you should e.g. not be able to close or set new labels to a random issue and not be able to push to WhereYouGo. Could you test that?

Confirming that I can't set labels or close issues on WhereYouGo. So access rights seem to work

**Comment by Lineflyer** [comment]
Thanks @eddiemuc 

Will complete the tasks above now, so you have access again :)

**Comment by Lineflyer** [comment]
Setup done.
Please notify me, if you have less access as before.
I intentionally not providing access to @cgeo/team to WhereYouGo but created a dedicated team to allow seperate evolution of access rights between both repos. Of course everyone of the c:geo team can be provided the same access (if not already done during my migration).

@SchoolGuy  @sk-juroot 
I invited you to become member of @cgeo/whereyougo-team as you both provided very valuable contributions and hoping you will further contribute. The membership provides writing access rights to the Github project except merging PRs or directly pushing to master/release/legacy branches.
