### ISSUE TITLE
Integration with Locus no longer working

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/WhereYouGo#357]
### Describe your problem!

Users say, that instead of opening Locus it instead opens the browser on the GooglePlay page of Locus.

Maybe related to package visibility restrictions?

### How to reproduce?

Set to use Locus instead of internal map

### Actual result after these steps?

Google Play page opened instead of Locus

### Expected result after these steps?

Open Locus and show zone info

### Reproducible

Unclear

### WhereYouGo Version

2022.01.02

### System information

```text
Have asked the user
```

### Additional Information

Support ticket 182935

**Comment by sk-juroot** [comment]
Well, this is interesting. 

First, I was thinking, there will be some problem with outdated Locus api, which turned out true (WhereYouGo is using 0.2.7, current is 0.9.45). So there will be problem with users migrating to new Locus 4 app, which can't be detected properly with old library. Changed, synced, clean build, failed. 

Turned out, the whole logic of WhereYouGo handling available cartridges was made around Locus API `Waypoint` class, removed many versions ago. To fix the connection to Locus (if we want to preserve the ability to show WYG data on Locus map), we need to refactor logic for loading cartridges. This could be done along the way with #309 refactor.

**Comment by better-tester** [comment]
Hallo,

the same here, Android 12, Wherigo 14.01.2022. Using Locus Pro (3.56.5) with offline maps. Klicking on maps in Wherigo requires to be online and calls the Playstore. I got an error log from today - perhaps this will help. Does it matter whether Locus 4 or Locus Pro is installed? Thanks for keeping Wherigo alive. Uwe
[error.log](https://github.com/cgeo/WhereYouGo/files/7921058/error.log)

**Comment by Lineflyer** [comment]
Thanks @better-tester 
We know its not working :( ...we were not able to fix that issue with 2022.01.24 version due to lack of developers.

The best we have done for now is adding it to our FAQ: https://www.whereyougo.org/faq#locus

**Comment by bekuno** [comment]
@better-tester Can you test result of the PR #358: https://ci.cgeo.org/job/WhereYouGo-CI_commit-build/318/artifact/build/outputs/apk/debug/whereyougo-debug-dd3530d.apk ?
The migration looks codewise fine, but we need some more tests.

**Comment by better-tester** [comment]
> @better-tester Can you test result of the PR #358: https://ci.cgeo.org/job/WhereYouGo-CI_commit-build/318/artifact/build/outputs/apk/debug/whereyougo-debug-dd3530d.apk ? The migration looks codewise fine, but we need some more tests.

Guten Morgen :-); Android 12 is going to update the installed version and complains that the debug version is not valid (Whatever this means) and full stop. Installation from unauthorized sources was allowed. Any idea? I will uninstall the Playstore version and try again later on.

**Comment by better-tester** [comment]
> > @better-tester Can you test result of the PR #358: https://ci.cgeo.org/job/WhereYouGo-CI_commit-build/318/artifact/build/outputs/apk/debug/whereyougo-debug-dd3530d.apk ? The migration looks codewise fine, but we need some more tests.
> 
> Guten Morgen :-); Android 12 is going to update the installed version and complains that the debug version is not valid (Whatever this means) and full stop. Installation from unauthorized sources was allowed. Any idea? I will uninstall the Playstore version and try again later on.

**It works.** I can call Locus from the map icon on the landing page. For the rest (out of a running cartridge) I need a cartridge nearby but that's difficult in HomeOffice :-) 

Reason for refusing to install:
_Uninstall the dev version (or store version of the app). If you have an app with the same bundle id it will refuse to install a different variation of the sample app._ (Stackoverflow)

**Comment by bekuno** [comment]
> Reason for refusing to install: _Uninstall the dev version (or store version of the app). If you have an app with the same bundle id it will refuse to install a different variation of the sample app._ (Stackoverflow)

Correct.

**Comment by Lineflyer** [comment]
> Correct.

and caused by the fact, that all local builds (either on our CI or from https://github.com/cgeo/WhereYouGo/releases ) have a different signature as the production build from Google Play. This is due to the fact, that we publish the app under a foreign developer account and use intermediate certificates.

**Comment by better-tester** [comment]
Hello again - I'm caught by the Android SDK30/31 storage festival. The phone has no external SD card, so it is all under /storage/emulated/0... Up to now I had my own directory to store the .gwc files somewhere. I can change the debug-version to this folder, but the .gwc are not visible. Wherigo has the right to access media files - there is no option for all and every file. a) I move .gwc to Android/data/menion..Where../files, b) can wherigo make use of Android/ media/wherigo/files ? 

c:geo is able to read .map files from android/media/menion/mapsVector :-) sharing files is getting really tricky.

**Comment by Lineflyer** [comment]
@better-tester Yes, another to-be-done --> #309 

At this moment WhereYouGo is only still able to access random directories for GWC and maps if you migrated from older versions. On fresh installs those permissions are gone (due to the new restrictions). 

Its probably the most important thing to solve for a potential new release.

Luckily we have scoped storage already implemented in c:geo, so we have experience just a lack of helping hands to add the same functionality to WhereYouGo.

Any help is appreciated if you happen to have experience in Java/Android coding.
