### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by bekuno** [cgeo/WhereYouGo#38]
We target (latest with PR #36) the current requirements for google play.
I think that we should create a new version of WhereYouGo as soon as possible only with PR #32 and #36.

**Comment by kurly1** [comment]
I think this is a good idea to get a new version of WhereYouGo as soon as possible whit the mentioned PR.

I think it would also be a good idea to release PR #30 and PR #41 and maybe others as a Betaversion, to have them tested on a whither range of devices.

**Comment by bekuno** [comment]
A beta version is a good idea, also for the "restart" of WhereYouGo.

**Comment by Lineflyer** [comment]
I just checked the Play Console:
WhereYouGo used the beta channel in the past, so beta testers are subscribed (but only 236 users).
Still worth a try also to test if publish procedures and keys are working.

So now we would either need someone (having the key) to build the APK or complete the CI setup including a release build job which uses the official key.
@mucek4 @kumy

**Comment by Lineflyer** [comment]
BTW:
The branch handling in this case should be (same as in c:geo):
We merge required PRs to the master branch and then cut a release by merging master to release.

Currently the release branch is still representing the last version from @biylda, I just copied this status to a new branch legacy (as a backup).

**Comment by bekuno** [comment]
@Lineflyer Can you finish PR #31 ?

**Comment by Lineflyer** [comment]
No time at this moment.
Feel free to push to the branch I used for the corresponding PR.

**Comment by bekuno** [comment]
The PR  #44 is for preparing the next release.
Currently the version number is static defined as 0.10.0.

**Comment by bekuno** [comment]
> So now we would either need someone (having the key) to build the APK or complete the CI setup including a release build job which uses the official key.

It would be fine if at first someone can build the apk manuelly to create a beta version.

After that we can create the process for date based version numbers and automatic signing. (changes in build.gradle and CI)

**Comment by kumy** [comment]
I have created new CI jobs ~30min ago for release and nightly using the current unmodified repositories. Apk are signed using the cgeo key as the legacy whereyougo keys are not (yet) present on server. Process may be enhanced with updates to the gradle script, but the starting point is there. Should we upload the geneted apk on the server along with the cgeo builds?

**Comment by Lineflyer** [comment]
> Should we upload the generated apk on the server along with the cgeo builds?

You mean via FTP to download.cgeo.org? Yes, that would be fine.

@mucek4 Can you store the keys on the server (same process as for the cgeo key) so we can use them for nightlies?

**Comment by bekuno** [comment]
@kumy Many thanks for the new CI jobs.
Please have a look at the PR job. There are some errors.

**Comment by kumy** [comment]
@bekuno I'm already on it, it's related to the user @cgeo-bot not having permission on the repo. I'll workaround that until this is fixed using my own token…

May we use `next_release` as a common branch name to prepare release. Job could be the same as `release` but upload will not be triggered ;)

**Comment by bekuno** [comment]
> May we use `next_release` as a common branch name to prepare release. Job could be the same as `release` but upload will not be triggered ;)

This is not so for c:geo, isn't it?
@Lineflyer What do you mean?

**Comment by kumy** [comment]
no, it's not like that on cgeo. I came to this as current release branch behave differently at least in generated filenames than builds from master branch. So it's not easy to test `release` builds. This idea came from your PR #44 ;) which may help later while releasing new versions, some sort of dry-run.

**Comment by kumy** [comment]
@bekuno errors should be gone, but it's using my account instead of `cgeo-bot`.

@Lineflyer As we seems to have lost access to `cgeo-bot` (if that the case, we should revoke it's rights on all repo :/) should we create a new github bot account?

**Comment by Lineflyer** [comment]
> @Lineflyer As we seems to have lost access to cgeo-bot (if that the case, we should revoke it's rights on all repo :/) should we create a new github bot account?

Sounds like a good idea instead of hoping to get access.
Feel free to create a new one. Later on we could also use this as wel towards Codacy to resolve the workaround to use my own account.
If you need help contact me or @mucek4

**Comment by kumy** [comment]
The built binaries should be available at:
* http://download.cgeo.org/whereyougo-nightly.apk
* http://download.cgeo.org/whereyougo-release.apk (on next release :crossed_fingers:)
* Or on each Jenkins jobs

**Comment by bekuno** [comment]
@Lineflyer What about to make an official statement at the WhereYouGo google group about the current state (nightly available / plan for test version)?

**Comment by Lineflyer** [comment]
Will test the versions out next days and then probably communicate something somewhere.

**Comment by mucek4** [comment]
You tagged me 3 times, yet I missed those emails. I am adding signing keys now.

**Comment by mucek4** [comment]
Keystore added and jobs updated.

**Comment by Lineflyer** [comment]
Do we have a correctly signed version now as output of the CI?

@kumy 
I did not have the time to check in detail the configured CI jobs.
As stated earlier I would love to see he same mechanism we are used to use with c:geo, i.e. nightlies from `master` and the possibility to build RC and release versions based on `release`. 

As soon as we are able to build correctly signed RC versions I could merge branches and publish the resulting `release` state as a RC version on the beta channel of WhereYouGo.

**Comment by kumy** [comment]
Did you checked the new jobs? I think we are quite close to that. apk should be signed with right keys already ;)

**Comment by Lineflyer** [comment]
@kumy 
Thanks for the hint. I checked the jobs now. I downloaded and installed the nightly available on download.cgeo.org as of today. However it does not seem to contain the status of current `master`. 

Should I be able to see any version code somewhere to doublecheck? I do only see 0.9.3 within the app (about page) and also on my device app information panel.

**Comment by kumy** [comment]
That's strange, I confirm that NB job use `master` branch. The one built and uploaded to download.cgeo.org was built uppon `f08ac2d`

https://ci.cgeo.org/view/whereyougo/job/whereyougo%20(nightly)/17/console

**Comment by Lineflyer** [comment]
> If version is not reflected in binary app, then it should be something wrong with gradle script or something like that. Maybe @bekuno has any hint?

Its not (only) about the version, but e.g. looking at the about page, it misses the changes done with https://github.com/cgeo/WhereYouGo/pull/32

**Comment by Lineflyer** [comment]
Stop!
Google Play Protect fooled me by blocking the installation in the background. Sorry!

**Comment by kumy** [comment]
I just check the md5sum from the release available in jenkins and the one from download.cgeo.org, both are identical. I've downloaded and installed the one (but they are the same ;)) from jenkins, on first start I can see `0.10.0`. Not sure where your problem is.

**Comment by mucek4** [comment]
Signature of this new nightlies shall already be with WYG certificate. Can someone check that?

**Comment by Lineflyer** [comment]
For your attenation:
I just merged the master branch onto the release branch. 
Additionally the original last release by @biylda has been preserved into the branch legacy (for documentation purposes or fallback option).

This means:
- I will start to test a release candidate APK build from release, which can then be used for beta and finally publishing
- You can start to freely work on master and e.g. merge outstanding PRs unrelated to reviving the app

As to remind you:
We keep the same principle as we use for c:geo:
Main development takes place on the master branch, while release is the existing or upcoming release and only bugfixes should be done on that branch on demand.

**Comment by Lineflyer** [comment]
OK guys...I did publish a version to the beta channel of WhereYouGo.
There have been quite some warnings about old versions on the Play console (see #13), I deactivated all old versions for the beta channel (which solved the warnings).
So version [2020.03.05](https://github.com/cgeo/WhereYouGo/releases/tag/2020.03.05_RC) should be out there for subscribed beta testers, which are only 250 accounts by now. However this might be good to test the upgrade path and certificate chain. I will report back (I can test it as I also subscribed to the beta channel).

**Comment by bekuno** [comment]
The update worked perfectly.

**Comment by Lineflyer** [comment]
I just compiled another beta version 2020.03.08 which now also includes #72 and #71.
Map providers are looking good and working.

About to release to beta channel once again.
If nothing negative comes in we can do the first real life release next days.

**Comment by Lineflyer** [comment]
New beta 2020.03.08 went through beta upgrade smoothly. I checked maps working on several Android versions.
No user complaints, no new crashes on Google Play console.

I will go forward and (as we do not have a dedicated version naming for beta versions) promote the beta version to production version.
So 2020.03.08 will go live soon as our first productive version :)

I will report back here if release has been done.

**Comment by Lineflyer** [comment]
Wow, Google Play is fast tonight.

Version 2020.03.08 is live!!!
Thanks to all helping hands WhereYouGo is alive again!

I hope over time some people will join here to help keeping it alive and further improve it.

**Comment by moving-bits** [comment]
Guys, you're fantastic! Thank you for bringing WhereYouGo back into the game again!
