### ISSUE TITLE
Can't select custom Directory on Android 12

### ISSUE THREAD

**Issue by MakiWolf** [cgeo/WhereYouGo#383]
### Describe your problem!

On Android 12 when selecting a custom folder where a .gwc file is included the app says "No Whereigo cartige (*.gwc) 
is avilable. Dowload or copy them into directory".

Also on Android 12 I can't use the standard folder under android/data because i can't copy that file here. No write permission.
As a workaround I currently use allow all URLs in settings so that the dowload link will open in app.

Maybe there need something implementes like in cgeo when dowloading offline maps?

### How to reproduce?

1. Open settings
2. Global
3. Wherigo folder

### Actual result after these steps?

No Whereigo cartige (*.gwc) is avilable. Dowload or copy them into directory

### Expected result after these steps?

Should open file.

### Reproducible

Yes

### WhereYouGo Version

2022.01.14

### System information

```text
Samsung s21 Android 12
```

**Comment by Lineflyer** [comment]
Yes, thats an open issue covered by #309 

See https://www.whereyougo.org/faq#file_access for a workaround (=use default dir and let WhereYouGo download the cartridges for you).
