### ISSUE TITLE
Longitude is shown as latitude

### ISSUE THREAD

**Issue by rillig** [cgeo/WhereYouGo#391]
### Describe your problem!

When starting a new cartridge, the coordinates are shown as N 53.4 N 9.8, which is obviously wrong.

CartridgeDetailsActivity says:
~~~java
UtilsFormat.formatLatitude(MainActivity.cartridgeFile.longitude)
~~~

### How to reproduce?

Start a cartridge.

### Actual result after these steps?

N 53.4 N 9.8

### Expected result after these steps?

N 53.4 E 9.8

### Reproducible

Yes

### WhereYouGo Version

any

### System information

```text
any
```

**Comment by rillig** [comment]
Seems to be really hard to replace the wrong `formatLatitude` with the correct `formatLongitude` in the `CartridgeDetailsActivity`.

**Comment by SammysHP** [comment]
@rillig Do you like to open a pull request?

**Comment by rillig** [comment]
@SammysHP No, I don't, but thanks for asking.

**Comment by moving-bits** [comment]
> @SammysHP No, I don't, but thanks for asking.

This little bug dates back to 2012. That's community driven development - if no volunteer takes the time to fix it, it won't get fixed...
But for this one: See #419
