### ISSUE TITLE
Can't see *.gwc files in the directory

### ISSUE THREAD

**Issue by vegantriathlete** [cgeo/WhereYouGo#397]
### Describe your problem!

The app doesn't see the files in the selected directory even though they are placed there.

### How to reproduce?

1. Start WhereYouGo app
2. Click Settings > Global > Wherigo folder
3. Choose a location. For example, Downloads shows up as /storage/emulated/0/Downloads/
4. Download a *.gwc file from the wherigo.com site
5. Move the file into the selected Wherigo folder
6. Click Start in the WhereYouGo app

### Actual result after these steps?

Receive message:

No Wherigo cartridge (*.gwc) is available.
Download or copy them into "/storage/emulated/0/Downloads/". You can also set a path to custom directory in "Settings - Main - Wherigo folder." make sure you granted the application permission to write to external storage and you have write permission in selected directory. Some newer devices don't allow writing to SD card. If you're not sure, set "Wherigo folder" automatically.

### Expected result after these steps?

The files in the location should show up as choices.

### Reproducible

Yes

### WhereYouGo Version

2022.01.14

### System information

```text
Samsung, Galaxy A13, Android 12
```

**Comment by vegantriathlete** [comment]
![Screenshot_20220623-164155_WhereYouGo](https://user-images.githubusercontent.com/1111301/175427669-a8db4edc-601c-4610-bff2-ca3773828168.jpg)
![Screenshot_20220623-164130_Settings](https://user-images.githubusercontent.com/1111301/175427674-74f7151a-91c0-4cb0-a736-e3e0a52f6a9b.jpg)
![Screenshot_20220623-164039_My Files](https://user-images.githubusercontent.com/1111301/175427686-de8649f0-d161-4277-8e1c-b0c7fa4946e8.jpg)

**Comment by Lineflyer** [comment]
I assume you use a rather recent Android version. Unfortunately WhereYouGo is due to lack of developers not yet fully git for those version. There is a workaround available:
https://www.whereyougo.org/faq#file_access

**Comment by Lineflyer** [comment]
See #309 for root cause

**Comment by vegantriathlete** [comment]
@Lineflyer Can you elaborate more on the in-app download? I'm not running c:geo, only Whereyougo.

**Comment by vegantriathlete** [comment]
Also, the default points to /storage/emulated/0/Android/data/menion.android.whereyougo/files/. I can't see anything below Android/data when I use my file manager app, even if I change the settings to show hidden files.

**Comment by vegantriathlete** [comment]
Okay, I've even installed c:geo and I still end up on the website and it downloads into my Downloads folder. I can't find a way to get the downloads to end up in the location that default points to.

**Comment by vegantriathlete** [comment]
And thanks for picking up this project! I understand that it's just a small team of volunteers.

**Comment by Lineflyer** [comment]
This describes how you download cartridges directly with WhereYouGo: https://www.whereyougo.org/faq#login

Basically you need to click on a download link for a cartridge in your browser, which triggers WhereYouGo to download the cartridge by itself.

**Comment by vegantriathlete** [comment]
Unfortunately, when I click the Download link it just downloads it directly through the browser. It's not triggering WhereYouGo. I have entered my credentials in WhereYouGo and have verified that it can successfully log in.

**Comment by Lineflyer** [comment]
Probably you are running Android 12, where just another tweak is needed:
https://www.whereyougo.org/faq#android12_links

**Comment by vegantriathlete** [comment]
Thank you for your patience! Thank you, thank you, thank you!

For other people:
Make sure that in WhereYouGo you have entered your login credentials under Settings > Login credentials. Then run Check logiin data.
On your Android 12 phone, go to Settings > Apps. Select WhereYouGo. Select Set as default. Enable Open supported links. Check that the supported web addresses are turned on.

**Comment by allmynamesweretakenomoreideas** [comment]
I encountered the same issue on Android 13 (Xperia 1).
Thank you @vegantriathlete for the detailed explanation - this works for me.
![Screenshot_20230922-123447_1](https://github.com/cgeo/WhereYouGo/assets/17786012/f14864d9-b6a8-4611-bf7c-7762e01d67c3)
This is how the Link settings look at my device.
