### ISSUE TITLE
Fail to download cartridge

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/WhereYouGo#412]
### Describe your problem!

The current WhereYouGo version stopped downloading cartridges even with successful login.
This means, that on newer Android devices there is no possibility to use WhereYouGo to play cartridges, because
1. using a user-accesible dir for manual providing cartridges is not yet supported (no SAF)
2. download no longer working

I did not look into why its failing but there are user reports and I can reproduce, that cartridges are not loaded "Lädt herunter: Fehler".

### How to reproduce?

Try to download a cartridge in WhereYouGo (e.g. triggered by c:geo).

### Actual result after these steps?

It fails

### Expected result after these steps?

it should download the cartridge

### Reproducible

Yes

### WhereYouGo Version

2022.01.14

**Comment by wolverine007** [comment]
Could verify the issue from my side, received today a note for one of my caches.

Tried it therefore on several other WIGs, same result. 

Direct link to the Cartridge stored on offical wig repository is still working.
