### ISSUE TITLE
Cant download or import cartriges

### ISSUE THREAD

**Issue by Luky12568** [cgeo/WhereYouGo#443]
### Describe your problem!

I cant download or import .gwc files into specified folder

### How to reproduce?

From c:geo ([Cache](coord.info/GC5AC82) )opened whereyougo
Hit download
Connecting
Sign in...

### Actual result after these steps?

Error ![Screenshot_20230723-144903_WhereYouGo](https://github.com/cgeo/WhereYouGo/assets/75023813/2cb796c2-29e6-47b3-b3e6-89b9c26ac3f6)

### Expected result after these steps?

Continue downloading

### Reproducible

Unclear

### WhereYouGo Version

2023.02.22

### System information

```text
Samsung A41, android 11, from apk
```

**Comment by yagueto** [comment]
Might it be related to #152? Have you accepted the T&Cs on the website?

**Comment by Luky12568** [comment]
I can download it normally (btw where t&s)

**Comment by Lineflyer** [comment]
Please set the werigo folder to "default". 
As WhereYouGo is not yet fully compatible with newer Android versions a custom folder wont work.

**Comment by Luky12568** [comment]
Thx bro, I tried it like 10 times in default and it wouldn't work, and now it works
