### ISSUE TITLE
No where I go cartridge available

### ISSUE THREAD

**Issue by Musicpac** [cgeo/WhereYouGo#446]
### Describe your problem!

Upon tapping on start Where you go states that no cartridges were found in the data location.
All permissions are granted and in said location are 2 .gwc 

Issue exists on an Google Pixel 6 with newest Android. No SD Card is used

### How to reproduce?

1. Have a Google pixel 6
2. Download WhereYouGo through F-droid or play store
3. Change location to Accessible folder
4. ???
5. Error

### Reproducible

Yes

### WhereYouGo Version

2023.02.22

**Comment by rouroni1** [comment]
Confirm the issue. If I download de GWC I get always error when I try to Change the storage. The storage changes but dosen't show the cartgride.

Tested:
Poco F4GT --> Android 13 --> Chrome and Brave Browsers

Xiaomi Mi6 --> Android 13 (LineageOS) --> Chrome and Brave Browsers

**Comment by Lineflyer** [comment]
This is indeed a known issue (and covered here on Github already by corresponding feature requests).

In fact WhereYouGo is not fully compatible with newer Android versions.
The workaround is described here: https://www.whereyougo.org/faq#file_access

In fact you need to keep the default cartridge location and use WhereYouGo to download cartridges.
