### ISSUE TITLE
Can't change whereigo directory in whereyougo app

### ISSUE THREAD

**Issue by tdeshler** [cgeo/WhereYouGo#447]
### Describe your problem!

I have downloaded the .gwc file, but I can't get the app to access the file. 

### How to reproduce?

1. The app specifies a default directory that I don't see on my phone (does not exist). 
2. I tried to change the default directory for whereigo files in the settings of the app. 
3. From the settings (Global/Whereigo folder), I navigate to my chosen folder, then select ok, but the default folder remains specified, even after stopping and restarting the app.

### Expected result after these steps?

I expected to change the whereigo folder so I can access the .gwc file that I've downloaded.

### Reproducible

Yes

### WhereYouGo Version

2023.02.22

### System information

```text
Samsung A32 running Android 13
```

**Comment by SammysHP** [comment]
Right now you have to download the cartridge from inside Wher

**Comment by tdeshler** [comment]
I've tried that but getting an error:

Downloading: Error(/storage/emulated/0/Android/5165f3fc-8a48-4fbf-bda8-335684531bd6_not_so_colossal_ca.gwc:open failed: EPERM (Operation not permitted). 

The default download directory does not exist on my phone.

**Comment by SammysHP** [comment]
Do not change the download directory, just select "default". The directory will be created automatically in an app-private context.

**Comment by tdeshler** [comment]
Ok, it seemed to work that time. The default directory had already been specified, but I went to settings and specified default again and this time the cartridge downloaded successfully. Thanks for the help.

**Comment by SammysHP** [comment]
Yeah, internally it's a difference whether you press the "default" button or select the same directory from the file manager.
