### ISSUE TITLE
Nightly job on CI is using developer build version Name

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/WhereYouGo#58]
Lookin on CI and having installed the versions from different build jobs, I have seen, that nightly job builds with the addition "developer build" in the versionName.
It should be   date-NB-commitID

**Comment by bekuno** [comment]
The buildType "nightly" was added in PR #57.
@kumy The job needs a change, isn't it?

**Comment by kumy** [comment]
[Latest generated filename](https://ci.cgeo.org/view/WhereYouGo/job/whereyougo%20(nightly)/) is `whereyougo-2020.03.04-NB-9c329ca.apk`, which seems to match the requirement, I thought @Lineflyer  was referring to 

https://github.com/cgeo/WhereYouGo/blob/9c329ca120eb74508726e798ef88febc04fe478b/build.gradle#L64

**Comment by bekuno** [comment]
@Lineflyer refers to

https://github.com/cgeo/WhereYouGo/blob/9c329ca120eb74508726e798ef88febc04fe478b/build.gradle#L66-L71

(Line 68), without "developer build"

**Comment by Lineflyer** [comment]
What I did is, that I installed the nightly version produced by CI and the about dialog in the app shows ".......-developer build" as versionName.

**Comment by bekuno** [comment]
`[workspace] $ "/srv/jenkins/jobs/whereyougo (nightly)/workspace/gradlew" -Pandroid.injected.signing.store.file=/srv/whereyougo.keystore -Pandroid.injected.signing.store.password=**** -Pandroid.injected.signing.key.alias=whereyougo -Pandroid.injected.signing.key.password=**** clean assembleDebug`
=> change to `assembleNightly`

**Comment by bekuno** [comment]
@kumy Can you change it?

**Comment by kumy** [comment]
I thought the change was already done by @bekuno.

Done!

**Comment by bekuno** [comment]
@kumy 
How can I do that from the Jenkins website?
I assumed that this is only possible with shell access.

**Comment by kumy** [comment]
No need shell access, just edit the job when you are logged in.

**Comment by bekuno** [comment]
Where?
I do only this points:
![grafik](https://user-images.githubusercontent.com/32555742/76168615-c9057c00-6171-11ea-8c4a-b2a33a57ec9f.png)

**Comment by kumy** [comment]
You seem to miss the admin privilege. I'll check later when at home. Unless someone else grant you the permission (@Lineflyer?)

**Comment by kumy** [comment]
@bekuno please check jenkins again.

**Comment by bekuno** [comment]
Now there are more entries :)
