### ISSUE TITLE
Create support environment for WhereYouGo

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/WhereYouGo#62]
The following could be done (feedback welcome):

- [x] Create a facebook page for WhereYouGo (currently not existing)
   This has just been [done](https://facebook.com/android.wherigo) and I invited @mucek4 as second administrator
- [x] Create a new mailbox (e.g. whereyougo@cgeo.org) to channelize support mails rather than using the current Google Group, which we cannot adminsitrate/moderate
- [x] Create a homepage

**Comment by mucek4** [comment]
I can create the email, however we can also try to a domain. whereyougo.dev sounds nice,

**Comment by bekuno** [comment]
For me as more "technican" the adress whereyougo@cgeo.org sounds fine.
But maybe users can have a problem to difference between c:geo as organization and c:geo (and send2cgeo) and WhereYouGo as single products (apps).
As first step I favor to set up whereyougo@cgeo.org and https://www.cgeo.org/whereyougo .
A adress like whereyougo.dev can then linked to this adress.

**Comment by jakedot** [comment]
@mucek4 have you set up the whereyougo@cgeo.org address in the meantime? I think it would be sufficient.

**Comment by Lineflyer** [comment]
> For me as more "technican" the adress whereyougo@cgeo.org sounds fine.

I agree.

> As first step I favor to set up whereyougo@cgeo.org and https://www.cgeo.org/whereyougo .

@mucek4 Please knodge me if you set up such mailbox. As time permits I will try to pull the mails also to the ticket system (maybe into a dedicated queue or whatever OSticket provides for such two subject use case).

>A adress like whereyougo.dev can then linked to this adress.

A new domain also costs money, therefore IMHO we can stick with the one we have.

**Comment by Lineflyer** [comment]
@mucek4 
I prepared the OSTticket environment accordingly. In fact I created a second "support department" WhereYouGo and renamed the default to "c:geo". 
It should also allow to add users specifically giving access to tickets from a single or both departments, if someone here is interested to take care of answering WhereYouGo support mails later on.

Once I configured the ticket pull with your sever details it will assign tickets from whereyougo@cgeo.org automatically to the WhereYouGo department with adapted auto-reply, etc. Thats the theory, need to test though.

**Comment by mucek4** [comment]
Hey. I have created the email and configured it into same email box. So both emails are stored into same account and retrieved with single user & pass. Try it out.

**Comment by Lineflyer** [comment]
Support channel set up, thanks to @mucek4 
Whereyougo@cgeo.org now going to dedicated IMAP mailbox, then pulled into my OS ticket installation under separate department (with own auto reply and header/footer). Need to fine tune a bit, but ready to be communicated.

If someone wants to have access I may need to change a bit (as currently only admin level can login), but just tell me, if someone of the team wants to have acccess.

**Comment by Lineflyer** [comment]
All done here.
