### ISSUE TITLE
Consolidate Release Notes

### ISSUE THREAD

**Issue by bekuno** [cgeo/WhereYouGo#63]
The Release Notes are currently maintained on 3 places
- README.md (version 0.10.0 changes in the "new" part)
- main/assets/news.txt (only version 2020.03.05 text)
- _data/changelog_en.txt /changelog_de.txt (only version 0.10.0 changes)

This need to be harmonised.

**Comment by Lineflyer** [comment]
The changelog in `README.md` is no longer needed. Its not used in the app and for documentation of releases on Github I already started using tags and releases, which is IMHO the better way.

AFAICS the `news.xml` is used to populate the changelog in the about dialog as well as in the "first start" dialog. 

I assume the `changelog_de.txt` was used to C&P it to the Google Play entry when doing a release. It could be useful to have those uploaded to Crowdin (as also the app description in the same directory).

So in a first step I will remove the changelog from `README.md` and align the others manually.

**Comment by Lineflyer** [comment]
FYI: I emptied the files `_data/changelog_*.txt` for now as its doubled effort to keep this up to date in addition to `news.xml`. So for now `news.xml` is the place for release notes.

Might be changed later if we include more files to crowdin translations.
