### ISSUE TITLE
Initial info screen has wrong button text to close the window

### ISSUE THREAD

**Issue by bekuno** [cgeo/WhereYouGo#7]
![Screenshot_20200112-150735](https://user-images.githubusercontent.com/32555742/72220963-869b3680-3556-11ea-989d-437fdb4d2d36.png)

**Comment by Lineflyer** [comment]
Interesting enough my WhereYouGo (installed from Google Play) has the correct label.

**Comment by bekuno** [comment]
> Interesting enough my WhereYouGo (installed from Google Play) has the correct label.

Ther are two info screens - one is only shown after fresh install (this issue), the other is from inside WhereYouGo (what I assume that you checked) with a close button.
