### ISSUE TITLE
Don't start with empty map

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/WhereYouGo#74]
**Describe the bug:**
After installation of WhereYouGo and selecting "Map" from the main menu the user only sees an empty map.

**To Reproduce:**
1. Install WhereYouGo and start it
2. Select "Map" from the main menu

**Actual behavior/state after performing these steps:**
You will see an empty map screen and have to manually select the map source (once, then saved) to finally see the map.

**Expected behavior/state after performing these steps:**
For a good user experience we should set a default online map source.

**Version of WhereYouGo used:**
2020.03.08

**Is the problem reproducible:**
Yes

**Comment by jakedot** [comment]
I changed the default map to OpenStreetMap.
