### ISSUE TITLE
Larger graphics for offline maps on high-res displays

### ISSUE THREAD

**Issue by andrixnet** [cgeo/WhereYouGo#76]
On high res displays, such as the Samsung S9+, offfline map is rendered at native pixel resolution which makes it almost unreadable because of high ppi density
![Screenshot_20200310-114659](https://user-images.githubusercontent.com/3382777/76300164-f1ea5600-62c4-11ea-876c-c391ebb4adf3.jpg)

AFAIK this has been dealt with in c:geo.
Also related to https://github.com/cgeo/WhereYouGo/issues/73

**Comment by Lineflyer** [comment]
This should be the needed fix done for c:geo which could maybe also applied to WhereYouGo:
https://github.com/cgeo/cgeo/pull/7753

@jonas-koeritz What do you think?

**Comment by moving-bits** [comment]
@andrixnet  Are you talking about the graphics / icons or about the text labels?
At first I thought the former, therefore I created a separate issue (#141) and PR (#142) for the text, but after rereading, I'm unsure.

**Comment by Lineflyer** [comment]
Continuing in #352
