### ISSUE TITLE
Upload to F-Droid

### ISSUE THREAD

**Issue by steffen-AEI** [cgeo/WhereYouGo#79]
I know a number of people using a Google-free (as much as possible) smartphone for geocaching, and like c:geo, WYG should be available for them. Are there plans to upload to F-Droid, or provide a separate repo, in addition to releases on GitHub?

**Comment by andrixnet** [comment]
I'd ask the same about Aptoide as well

**Comment by Lineflyer** [comment]
Lets continue in #151. Will open a new issue for aptoide.
