### ISSUE TITLE
Spotaneous crashes on zone and item interaction

### ISSUE THREAD

**Issue by jakedot** [cgeo/WhereYouGo#86]
**Describe the bug:**
A friend submitted the following recordings to me via WA and commented:

> This happens on any cartridge, some stored months ago, some recently [test builds for unpublished caches].
> 
> After some short time in the cartridge, it seems to happen on an interaction with zones or items, I'm booted out back to the main menu. _(The error message "invalid cartridge" that pops up is appearing since I had messed up a cartridge some earlier time, but it didn't go away after fixing it. It should not be related with the current problem)_.
> 
> The folder is set to the Android Downloads so I can download cartridges via browser and have them available in the app immediately [workaround for the not working direct download in the time before the update].
> 
> The problem seems independent of the cartridge source, e.g. local test build or website download.
> 
> This happens only since the update (they hadn't used the beta).
> 
> On a secondary device, this problem is not present [and on my device it's also not present].

**Is the problem reproducible:**
No

**To (possibly) Reproduce:**
1. Set the cartridges directory to the Android Downloads folder.
2. Download and start some cartridge
3. Interact with zones or items
4. Crash without specific error message

**Actual behavior/state after performing these steps:**
Cartridges are stopped spontaneously.

**Expected behavior/state after performing these steps:**
Cartridges should run smoothly.

**Version of WhereYouGo used:**
08.03.2020 release, errors on Huawei P10 lite, no problems on Samsung J415FN and Galaxy S4.

**Screenshots:**

![WhatsApp-Video-2020-03-15-at-133](https://user-images.githubusercontent.com/12250212/76711365-b231cd00-670f-11ea-877f-72b70b95a747.gif) ![WhatsApp-Video-2020-03-15-at-230](https://user-images.githubusercontent.com/12250212/76711623-f6be6800-6711-11ea-96d0-77964b61700c.gif)

**Additional context:**
I think I have seen similar reports of varying verbosity on [the Facebook page](https://www.facebook.com/android.wherigo/).

**Comment by jakedot** [comment]
The problem persists after deleting the app's storage and/or reinstalling, although one of those steps fixed the "invalid cartridge" error message.

![WhatsApp-Video-2020-03-16-at-193](https://user-images.githubusercontent.com/12250212/76798771-7f034280-67d0-11ea-94e1-48f41a7b9ec3.gif)

BTW, the user was not able to find any error log for this behaviour.

Might well be related to #65.

**Comment by Lineflyer** [comment]
If it is an Android 8 device it is probably a duplicate. In that case we should stick to one of these issues.

@jakedot Can you try to get the error.log (which I learned exists in the GWC directory)

**Comment by jakedot** [comment]
Yes, Android 8.0.0. The user claimed there was none, see above comment, I already had them look for it. And after the storage wipe, the old info would now be lost. Sorry, I thought they backupped the directories.

Closing here for now, it should be linked in the other issue anyway.

**Comment by jakedot** [comment]
@Lineflyer Problem does not occur with the 0.9.3 beta. Indicating that this specific problem was caused by the changes between then and last release.
